### PR TITLE
Repo and CI changes to encourage a new release

### PR DESCRIPTION
**Pull request by adamvoss**
This updates repository a little to reflect GitHub conventions and fix links.  This also does all I can with respect to automatically deployment.  See https://docs.travis-ci.com/user/deployment/pypi/ for adding the password needed to complete this.

This is done in hopes of getting a new release to resolve gpodder/gpodder#248.

### CODE REVIEW

**Comment by stefankoegl** [comment]
+1 to the changes so far.

Do we intend to implement automatic deployment as part of that pull request? If so, we should clarify which user should publish the build (maybe a generic `gpodder` user?), and which version it would publish. If that's not in scope of that pull request, it can be merged as is.

**Comment by adamvoss** [comment]
@stefankoegl I am not sure I understand well enough to answer your questions concisely, but might be able to answer you with enough explanation:

 - The goal of this PR is to implement automatic deployment as a way to make it easier on the project maintainer to release new build.  (Because I want a new build :grin:)
 - It only really automates the publishing to PyPI, the rest of the release process would be unchanged.
 - I set it up so releases happen based on tags.  There are other ways this could be done, but tags seem to be pretty typical and are automatically recognized by GitHub Releases as releases.  This means anyone with permission to push tags to the repository could trigger a release (I do not know if that list includes anyone other than you and @thp).
 - Right now, [it lists @thp as the package owner](https://pypi.python.org/pypi/mygpoclient) so this PR just needs him to encrypt his PyPI password and add it to **.travis.yml** to work (assuming my configuration is correct).
 - I am not familiar with the PyPI platform; but, looking at another package, it appears it does support multiple owners/maintainers, so @thp could add another user if desired.
 - Unless it is a signed or annotated tag, tags do not keep record of who created them (light-weight tags in git-terminology).
 - PyPI does not appear to indicate which owner pushed the package, it can only be assumed to be one of the owners listed on the site.

**Comment by stefankoegl** [comment]
Thanks for clarification. I've been reading up on automated releases, and I agree with your approach.

I have created neutral `gpodder` user on PyPI that we can use for automated deployments of `mygpoclient` and possibly also other projects. 

@adamvoss could you add this user with the following password to the Travis configuration?

````
  secure: "LhMmayKATJlyob0pkRvcDfie5vi8O+BdpMgJ224C+SXpwpQafPfHNUFzi3+IkS7z3KbYx/jTpP6gcfmEXnG/nI74U0U4fnY1KQixEfwcRTLHNDnx72qe4zXkXAtBzXCRROnyOTir1AolPiC8lpiL+ZBc8cBwan+322IZdlL8t5g="
````

@thp coudl you add the `gpodder` user on PyPI as a maintainer?

**Comment by thp** [comment]
Added `gpodder` on PyPI as maintainer for `mygpoclient` and `podcastparser`.

**Comment by elelay** [comment]
@adamvoss anything blocking the release?

**Comment by adamvoss** [comment]
@elelay There was a trivial merge conflict from changes made after I submitted this (which I just resolved), but AFAIK, this has just been waiting to be merged.

**Comment by elelay** [comment]
Merged, thanks! How do we go from there? I'm also eager to see the release happening.

**Comment by adamvoss** [comment]
Since you had permission to merge this, you probably have permission to push a tag and trigger a new release if it comes down to it.

**Comment by thp** [comment]
Done here: https://github.com/gpodder/mygpoclient/commit/f3feadad6f71bf6605a09f65ec00deb2e53a0c84

**Pull request merged**
