### PR TITLE
Add Sphinx docs from Wiki

### PR DESCRIPTION
**Pull request by stefankoegl**
To complete gpodder/gpodder.github.io#9, I have added the [mygpoclient docs](http://wiki.gpodder.org/wiki/Web_Services/API/Reference) using sphinx.

I have not changed any contents so far, but just adapted it to reStructuredText and added links to module docs, etc.

The docs should be ready for publishing on http://readthedocs.io/.

### CODE REVIEW

**Comment by adamvoss** [comment]
Sweet!  Thanks for taking care of this! (NB. did not actually build or inspect anything)

Three minor things that would be good to do once this is live:  

* Update the README to include a url to the published site
* Add the published site as the website for this repository (can be set by editing the project description at the top of the main repository page)
* Update the gPodder website url (http://gpodder.github.io/mygpoclient) to redirect the published site (I assume, if you think it is better to keep it at the GitHub repo, that is good too.

**Comment by stefankoegl** [comment]
Thanks for the feedback!

> Update the README to include a url to the published site

Done in a7b29b2596ce94ad7b96610a5b8b5755fc70160f

> Add the published site as the website for this repository (can be set by editing the project description at the top of the main repository page)

Done

> Update the gPodder website url (http://gpodder.github.io/mygpoclient) to redirect the published site (I assume, if you think it is better to keep it at the GitHub repo, that is good too.

That'd be up to @thp to decide / change.


> Disable the GitHub Wiki for this project

Why? I don't think having docs necessarily makes the wiki redundant.

**Comment by adamvoss** [comment]
@stefankoegl Awesome!

> > Disable the GitHub Wiki for this project
> Why? I don't think having docs necessarily makes the wiki redundant.

It looks like you disabled the wiki anyway, but my main reasoning was as follows:
The wiki becomes another thing to manage/maintain.  Either it is open to everyone and without monitoring it you don't know what gets posted there, or it is restricted to collaborators so there are very few people who can actually edit it while the docs can be updated by anyone via pull request.  If both are active, you have two potential sources of truth, and the question becomes what content should go in which place.
All of these complexities are avoided by disabling the wiki.  Even if it was going to sit empty, disabling it removes the tab so people interested in the project are saved from needing to click it to see if anything is there and it can always be re-enabled later.

**Comment by thp** [comment]
I did the disabling yesterday (forgot to post here), and fully agree with your reasoning :)

**Comment by stefankoegl** [comment]
OK, agreed :)

**Pull request merged**
